name: Shoe-Store React App deploy to surge
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Installs Node JS
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-versio: 12 
    
      # Installs React dependencies
      - name: Install pakages
        run: npm install

      # Builds the App
      - name: Build React App
        run: |
          npm install # Install Dependencies
          CI=false npm run build # CI=false to ignore warnings
          
      # Installs Surge
      - name: Install surge
        run: sudo npm install -g surge

      # Deploys to Surge
      - name: Deploy to surge
        run: surge ./build shoe-store-1999.surge.sh --token ${{ secrets.SURGE_TOKEN }}
